---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Ansible CLI
        uses: tomasnorre/ansible-cli-client@0.0.2
        with:
          command: |
            playbooks/adhoc/setup-environment.yml
